/* eslint-disable */
// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/[lng]/page.info";
import * as VaultPageRoute from "@/app/[lng]/[vault]/page.info";

export const Home = makeRoute(
  "/[lng]",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const VaultPage = makeRoute(
  "/[lng]/[vault]",
  {
    ...defaultInfo,
    ...VaultPageRoute.Route
  }
);

