/* eslint-disable */
// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/[lng]/page.info";
import * as VaultPageRoute from "@/app/[lng]/[vault]/page.info";
import * as WelcomeRoute from "@/app/[lng]/welcome/page.info";
import * as ApiTonClientPathRoute from "@/app/api/ton-client/[...path]/route.info";

export const Home = makeRoute(
  "/[lng]",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const VaultPage = makeRoute(
  "/[lng]/[vault]",
  {
    ...defaultInfo,
    ...VaultPageRoute.Route
  }
);
export const Welcome = makeRoute(
  "/[lng]/welcome",
  {
    ...defaultInfo,
    ...WelcomeRoute.Route
  }
);
export const ApiTonClientPath = makeRoute(
  "/api/ton-client/[...path]",
  {
    ...defaultInfo,
    ...ApiTonClientPathRoute.Route
  }
);

