// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod';
import { makeRoute } from './makeRoute';

const defaultInfo = {
  search: z.object({}),
};

import * as HomeRoute from '@/app/[lng]/page.info';

export const Home = makeRoute('/[lng]', {
  ...defaultInfo,
  ...HomeRoute.Route,
});
